### ISSUE TITLE
Quick menu manual button covers bottom bar descriptions

### ISSUE THREAD

**Issue by elluminance** [conorlawton/nax-ccuilib#10]
![image](https://github.com/conorlawton/nax-ccuilib/assets/49847844/48b78739-6d07-4a4e-81f6-debbd440007a)

This, for example, completely covers item descriptions meaning it's impossible to see how much an item heals in combat. 

![image](https://github.com/conorlawton/nax-ccuilib/assets/49847844/ebf52ed6-3a63-41fb-8481-4b7fe2fed788)

This applies to all quick menus - for example, the party AI control descriptions are covered.

**Comment by krypciak** [comment]
Should be fixed in #9, since the help menu was moved from the button (the button is now gone) to the mod's CCModManager options menu.
