### ISSUE TITLE
Quick Menu controls select the wrong button

### ISSUE THREAD

**Issue by cutiexe** [conorlawton/nax-ccuilib#2]
I finally isolated this quick menu issue to this mod. When CCUILib is active, the controls the quick menu seem to be rotated one slot counter-clockwise. Meaning, when I hold left on the analog stick or the A key to select Inspect in the left slot, the game instead selects the Item menu in the top slot.
I'm running Windows 11 with a Ryzen 7 5700G CPU and an RX 6750 XT graphics card, all drivers updated. If you need any more info about my specs or anything, please let me know!

**Comment by conorlawton** [comment]
When I wrote the quick menu change initially, I didn't consider controller support. Presently the controller actions are mapped to the four directional controls. The question now is how we should consider implementing the addition of quick menu buttons such that it works for both keyboard, keyboard + mouse, and controller. The simple fix would be to map it to the angle of analogue stick axes, which is what I think I'll do initially.

**Comment by Treeways** [comment]
Yeah, that would be great. Here's a video of the bug for reference:

https://github.com/conorlawton/CCUILib/assets/56928485/cd6239fd-05b8-4984-9922-4854ed609e56

**Comment by conorlawton** [comment]
Fixed in v1.2.2
